# -*- coding: utf-8 -*-
"""Resnet50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rfLSb0cZJ9ix9QhN4MaHerSKdnw8NaWG
"""

def load_image(image_path):
    img = tf.io.read_file(image_path)
    img = tf.io.decode_jpeg(img, channels=3)
    img = tf.keras.layers.Resizing(224, 224)(img)
    img = tf.keras.applications.resnet.preprocess_input(img)
    return img, image_path

image_model = tf.keras.applications.resnet50.ResNet50(include_top=False,
                                                weights='imagenet')
new_input = image_model.input
hidden_layer = image_model.layers[-1].output 

image_features_extract_model = tf.keras.Model(new_input, hidden_layer)